from pathlib import Path

from opencode_agent.memory import MemoryStore


def test_memory_keeps_recent_messages_in_order(tmp_path: Path) -> None:
    store = MemoryStore(tmp_path / "memory.sqlite3")
    store.add_message("chan", "user", "first")
    store.add_message("chan", "assistant", "second")

    context = store.get_context("chan", "anything", recent_limit=10)

    assert context.recent_messages == [("user", "first"), ("assistant", "second")]


def test_memory_limits_recent_messages_by_token_budget(tmp_path: Path) -> None:
    store = MemoryStore(tmp_path / "memory.sqlite3")
    store.add_message("chan", "user", "first " + ("x" * 80))
    store.add_message("chan", "assistant", "second")
    store.add_message("chan", "user", "third")

    context = store.get_context("chan", "anything", recent_limit=10, recent_token_budget=8)

    assert context.recent_messages == [("assistant", "second"), ("user", "third")]


def test_memory_truncates_single_recent_message_over_budget(tmp_path: Path) -> None:
    store = MemoryStore(tmp_path / "memory.sqlite3")
    store.add_message("chan", "user", "prefix " + ("x" * 200))

    context = store.get_context("chan", "anything", recent_limit=10, recent_token_budget=12)

    assert len(context.recent_messages) == 1
    assert context.recent_messages[0][1].startswith("[older text truncated]")


def test_autogenerated_retrieval_memories_are_not_in_context(tmp_path: Path) -> None:
    store = MemoryStore(tmp_path / "memory.sqlite3")
    store.add_memory("chan", "The deployment target is fly.io with a staging app.")
    store.add_memory("chan", "The favorite editor is vim.")

    context = store.get_context("chan", "How should deployment work for staging?", recent_limit=0)

    assert context.retrieved_memories == []


def test_pinned_memories_are_not_in_context(tmp_path: Path) -> None:
    store = MemoryStore(tmp_path / "memory.sqlite3")
    store.record_pinned_memory("User is allergic to peanuts.")

    context = store.get_context("other-channel", "unrelated query", recent_limit=0)

    assert context.pinned_memories == []


def test_pinned_memories_prune_oldest_under_limit(tmp_path: Path) -> None:
    store = MemoryStore(tmp_path / "memory.sqlite3")
    for index in range(105):
        store.record_pinned_memory(f"memory {index}")

    pinned = store.list_pinned_memories()

    assert len(pinned) == 99
    assert pinned[0] == "memory 6"
    assert pinned[-1] == "memory 104"


def test_summary_tracks_checkpoint(tmp_path: Path) -> None:
    store = MemoryStore(tmp_path / "memory.sqlite3")
    store.add_message("chan", "user", "remember project alpha")
    rows = store.unsummarized_messages("chan")
    store.upsert_summary("chan", "Project alpha matters.", rows[-1][0])

    assert store.get_context("chan", "", recent_limit=0).summary == "Project alpha matters."
    assert store.count_messages_since_summary("chan") == 0


def test_last_contact_is_persisted(tmp_path: Path) -> None:
    store = MemoryStore(tmp_path / "memory.sqlite3")

    store.set_last_contact("discord-channel")

    assert store.get_last_contact() == "discord-channel"


def test_document_index_retrieves_relevant_chunks(tmp_path: Path) -> None:
    store = MemoryStore(tmp_path / "memory.sqlite3")
    store.index_document(
        "docs/runbook.md",
        "Deployments use blue green rollout.\n\nBilling incidents use the stripe webhook runbook.",
    )

    results = store.search_documents("How do billing stripe incidents work?")

    assert results
    assert results[0].startswith("[docs/runbook.md#")
    assert "stripe webhook" in results[0]


def test_document_index_replaces_existing_source(tmp_path: Path) -> None:
    store = MemoryStore(tmp_path / "memory.sqlite3")
    store.index_document("docs/runbook.md", "old kubernetes notes")
    store.index_document("docs/runbook.md", "new fly.io notes")

    assert store.search_documents("kubernetes") == []
    assert "fly.io" in store.search_documents("fly notes")[0]
